LOG_CHANNEL( Debug, LOG_FOREGROUND_GREY ),
LOG_CHANNEL( Warning, LOG_FOREGROUND_YELLOW | LOG_FOREGROUND_INTENSITY ),
LOG_CHANNEL( Error, LOG_FOREGROUND_RED | LOG_FOREGROUND_INTENSITY ),
LOG_CHANNEL( Filesystem, LOG_FOREGROUND_GREY ),
LOG_CHANNEL( ShaderCompiling, LOG_FOREGROUND_GREY )